-- Migration 022: Study tools — persistent flashcards with spaced repetition (SM-2)
-- and per-topic study progress tracking (weak-topic detection).
--
-- flashcards: generated by the AI tool or added manually. SRS state follows the
-- SM-2 algorithm (interval_days, ease_factor, repetitions, lapses, due_at).
-- study_progress: one row per (user_id, topic). Updated whenever the tutor
-- records a quiz answer outcome; mastery_level is a 0..1 EMA of correctness.

-- ── Flashcards ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS flashcards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  textbook_id UUID REFERENCES textbooks(id) ON DELETE SET NULL,
  course_id UUID REFERENCES student_courses(id) ON DELETE SET NULL,
  topic TEXT NOT NULL DEFAULT '',
  section_path TEXT,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'ai' CHECK (source IN ('ai', 'manual')),
  -- SM-2 scheduling state
  interval_days FLOAT NOT NULL DEFAULT 0,
  ease_factor FLOAT NOT NULL DEFAULT 2.5 CHECK (ease_factor >= 1.3),
  repetitions INT NOT NULL DEFAULT 0,
  lapses INT NOT NULL DEFAULT 0,
  due_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, question)
);

CREATE INDEX IF NOT EXISTS idx_flashcards_user_due
  ON flashcards(user_id, due_at ASC);
CREATE INDEX IF NOT EXISTS idx_flashcards_user_course
  ON flashcards(user_id, course_id);
CREATE INDEX IF NOT EXISTS idx_flashcards_user_topic
  ON flashcards(user_id, topic);

ALTER TABLE flashcards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own flashcards" ON flashcards
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ── Study progress (weak-topic tracking) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS study_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id UUID REFERENCES student_courses(id) ON DELETE SET NULL,
  textbook_id UUID REFERENCES textbooks(id) ON DELETE SET NULL,
  topic TEXT NOT NULL,
  correct_count INT NOT NULL DEFAULT 0,
  incorrect_count INT NOT NULL DEFAULT 0,
  -- Exponential moving average of correctness in [0, 1]. Lower = weaker.
  mastery_level FLOAT NOT NULL DEFAULT 0.5,
  last_outcome BOOLEAN,
  last_quizzed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, topic)
);

CREATE INDEX IF NOT EXISTS idx_study_progress_user_mastery
  ON study_progress(user_id, mastery_level ASC);
CREATE INDEX IF NOT EXISTS idx_study_progress_user_course
  ON study_progress(user_id, course_id);

ALTER TABLE study_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own study progress" ON study_progress
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
