-- Migration 025: Reduce embedding dimensions 9692 -> 1536 (MRL) + add HNSW indexes
--
-- Background:
--   Old pipeline zero-padded Gemini's native 3072-dim embeddings to match a
--   VECTOR(9692) column. Zero-padding preserves cosine ranking but wastes 3x
--   storage and blocks indexing entirely (pgvector hnsw max = 2000 dims,
--   halfvec expression index max = 4000).
--
-- This migration:
--   1. Converts all four embedding columns to VECTOR(1536). Only
--      textbook_chunks holds rows (262) — their embeddings are nulled and
--      regenerated by scripts/reembed-all.mts after this migration.
--   2. Recreates the two typed-parameter RPCs with UNtyped `vector` params so
--      future dimension changes never require touching function bodies.
--   3. Adds HNSW indexes (cosine) on every embedding column.

-- ── 1. Column conversions ───────────────────────────────────────────────────
UPDATE public.textbook_chunks SET embedding = NULL;
ALTER TABLE public.textbook_chunks ALTER COLUMN embedding TYPE vector(1536);

ALTER TABLE public.textbook_page_summaries ALTER COLUMN embedding TYPE vector(1536);
ALTER TABLE public.documents ALTER COLUMN embedding TYPE vector(1536);
ALTER TABLE public.message_embeddings ALTER COLUMN embedding TYPE vector(1536);

-- ── 2. Untyped-param RPC recreations ────────────────────────────────────────

-- hybrid_search_textbook_chunks (RRF three-way fusion, migration 024 body)
CREATE OR REPLACE FUNCTION public.hybrid_search_textbook_chunks(
  query_embedding vector,
  query_text TEXT,
  p_textbook_id UUID,
  p_user_id UUID,
  p_match_threshold DOUBLE PRECISION DEFAULT 0.05,
  p_match_count INTEGER DEFAULT 10,
  p_page_start INTEGER DEFAULT NULL::integer,
  p_page_end INTEGER DEFAULT NULL::integer
)
RETURNS TABLE (
  id BIGINT,
  content TEXT,
  page_number INTEGER,
  structure_path TEXT,
  figure_refs JSONB,
  final_score DOUBLE PRECISION
)
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  WITH normalized_query AS (
    SELECT normalize_arabic(query_text) AS q
  ),
  vector_results AS (
    SELECT
      tc.id, tc.content, tc.page_number, tc.structure_path, tc.figure_refs,
      1 - (tc.embedding <=> query_embedding) AS similarity,
      ROW_NUMBER() OVER (ORDER BY 1 - (tc.embedding <=> query_embedding) DESC) AS rank
    FROM textbook_chunks tc
    JOIN textbooks tb ON tb.id = tc.textbook_id
    CROSS JOIN normalized_query nq
    WHERE tc.textbook_id = p_textbook_id
      AND tb.user_id = p_user_id
      AND tc.embedding IS NOT NULL
      AND 1 - (tc.embedding <=> query_embedding) > p_match_threshold
      AND (p_page_start IS NULL OR tc.page_number >= p_page_start)
      AND (p_page_end IS NULL OR tc.page_number <= p_page_end)
    ORDER BY similarity DESC
    LIMIT 20
  ),
  bm25_results AS (
    SELECT
      tc.id, tc.content, tc.page_number, tc.structure_path, tc.figure_refs,
      ts_rank_cd(tc.content_tsv, plainto_tsquery('simple', nq.q)) AS bm25_score,
      ROW_NUMBER() OVER (ORDER BY ts_rank_cd(tc.content_tsv, plainto_tsquery('simple', nq.q)) DESC) AS rank
    FROM textbook_chunks tc
    JOIN textbooks tb ON tb.id = tc.textbook_id
    CROSS JOIN normalized_query nq
    WHERE tc.textbook_id = p_textbook_id
      AND tb.user_id = p_user_id
      AND tc.content_tsv @@ plainto_tsquery('simple', nq.q)
      AND (p_page_start IS NULL OR tc.page_number >= p_page_start)
      AND (p_page_end IS NULL OR tc.page_number <= p_page_end)
    ORDER BY bm25_score DESC
    LIMIT 20
  ),
  trgm_results AS (
    SELECT
      tc.id, tc.content, tc.page_number, tc.structure_path, tc.figure_refs,
      similarity(tc.content, nq.q) AS trgm_score,
      ROW_NUMBER() OVER (ORDER BY similarity(tc.content, nq.q) DESC) AS rank
    FROM textbook_chunks tc
    JOIN textbooks tb ON tb.id = tc.textbook_id
    CROSS JOIN normalized_query nq
    WHERE tc.textbook_id = p_textbook_id
      AND tb.user_id = p_user_id
      AND tc.content % nq.q
      AND (p_page_start IS NULL OR tc.page_number >= p_page_start)
      AND (p_page_end IS NULL OR tc.page_number <= p_page_end)
    ORDER BY trgm_score DESC
    LIMIT 20
  ),
  combined AS (
    SELECT v.id, v.content, v.page_number, v.structure_path, v.figure_refs,
      v.similarity, b.bm25_score, t.trgm_score,
      (1.0 / (60 + v.rank)) AS rrf_vector, 0.0 AS rrf_bm25, 0.0 AS rrf_trgm
    FROM vector_results v
    LEFT JOIN bm25_results b ON v.id = b.id
    LEFT JOIN trgm_results t ON v.id = t.id

    UNION

    SELECT b.id, b.content, b.page_number, b.structure_path, b.figure_refs,
      v.similarity, b.bm25_score, t.trgm_score,
      0.0, (1.0 / (60 + b.rank)), 0.0
    FROM bm25_results b
    LEFT JOIN vector_results v ON b.id = v.id
    LEFT JOIN trgm_results t ON b.id = t.id
    WHERE v.id IS NULL

    UNION

    SELECT t.id, t.content, t.page_number, t.structure_path, t.figure_refs,
      v.similarity, b.bm25_score, t.trgm_score,
      0.0, 0.0, (1.0 / (60 + t.rank))
    FROM trgm_results t
    LEFT JOIN vector_results v ON t.id = v.id
    LEFT JOIN bm25_results b ON t.id = b.id
    WHERE v.id IS NULL AND b.id IS NULL
  ),
  scored AS (
    SELECT *,
      (0.7 * COALESCE(similarity, 0)
        + 0.3 * (COALESCE(bm25_score, 0) / (COALESCE(bm25_score, 0) + 1))) AS weighted_score,
      (rrf_vector + rrf_bm25 + rrf_trgm) AS rrf_score
    FROM combined
  )
  SELECT id, content, page_number, structure_path, figure_refs,
    (0.5 * weighted_score + 0.5 * rrf_score)::double precision AS final_score
  FROM scored
  ORDER BY final_score DESC
  LIMIT p_match_count;
$$;

-- match_textbook_page_summaries (Layer-1 page pre-filter, migration 020 body)
CREATE OR REPLACE FUNCTION public.match_textbook_page_summaries(
  query_embedding vector,
  p_textbook_id UUID,
  p_match_threshold FLOAT DEFAULT 0.3,
  p_match_count INT DEFAULT 5
)
RETURNS TABLE (
  page_number INT,
  summary TEXT,
  similarity FLOAT
)
LANGUAGE sql STABLE
SET search_path = public
AS $$
  SELECT ps.page_number, ps.summary,
    1 - (ps.embedding <=> query_embedding) AS similarity
  FROM textbook_page_summaries ps
  WHERE ps.textbook_id = p_textbook_id
    AND ps.embedding IS NOT NULL
    AND 1 - (ps.embedding <=> query_embedding) > p_match_threshold
  ORDER BY ps.embedding <=> query_embedding
  LIMIT p_match_count;
$$;

-- batch_update_embeddings: drop hardcoded ::vector(9692) cast
CREATE OR REPLACE FUNCTION public.batch_update_embeddings(
  p_updates JSONB,
  p_textbook_id UUID
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  item JSONB;
BEGIN
  FOR item IN SELECT jsonb_array_elements(p_updates)
  LOOP
    UPDATE textbook_chunks
    SET embedding = (item->>'embedding')::vector
    WHERE id = (item->>'id')::bigint
      AND textbook_id = p_textbook_id;
  END LOOP;
END;
$$;

-- ── 3. HNSW indexes ─────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_textbook_chunks_embedding_hnsw
ON public.textbook_chunks USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS idx_page_summaries_embedding_hnsw
ON public.textbook_page_summaries USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS idx_documents_embedding_hnsw
ON public.documents USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS idx_message_embeddings_hnsw
ON public.message_embeddings USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);
