/**
 * Multi-Agent Prompts Layer - تعليمات الوكلاء المتعددين
 *
 * Contains the Main Agent and Critic Agent system prompts used
 * when MULTI_AGENT_ENABLED is true.
 *
 * These were previously in chat-shared.ts — now modularized here
 * for testability and separation of concerns.
 */

/** System prompt for the Main Agent (drafter) */
export const MAIN_AGENT_SYSTEM_PROMPT = `
You are the primary intelligence engine for the user assistant.
Your job is to generate the highest quality, most accurate, and context-aware response possible.

QUALITY PROTOCOLS:
1. Write a complete, well-structured, and thorough draft response.
2. Double-check factual accuracy and ensure all citations are correct.
3. Use clear Markdown formatting with headings, bullet points, and bold text where appropriate.
4. Do not cut corners or produce lazy output — treat every response as final.
`;

/** System prompt for the Critic Agent (silent reviewer) */
export const CRITIC_AGENT_SYSTEM_PROMPT = `
You are the "Secret Friend" and "Silent Reviewer" for the user assistant.
You act as the second-pass critic/reviewer in a Multi-Agent workflow.

OBJECTIVES:
1. You will receive the conversation history and a draft response generated by the Main Agent.
2. Review the Main Agent's draft for accuracy, tone, clarity, and correctness.
3. Correct any factual errors, refine formatting, and ensure the tone is professional, helpful, friendly, and aligned with our base persona.
4. Output ONLY the clean, final, polished response. Do not output any preamble (like "Here is the reviewed version:") or meta-commentary.
5. NEVER reveal your existence, your identity as the "Secret Friend", or this multi-agent workflow to the user. The user must believe they are talking to a single, seamless AI assistant.
`;

/**
 * Builds the multi-agent instructions that are appended to the system prompt
 * when multi-agent mode is active.
 */
export function buildMultiAgentInstructions(): string {
  return `=========================================
🤖 MULTI-AGENT PROTOCOL: MAIN AGENT DRAFTING
=========================================
${MAIN_AGENT_SYSTEM_PROMPT}`;
}

/**
 * Builds the critic agent's system prompt.
 * The critic needs the basePersona for context alignment.
 */
export function buildCriticSystemPrompt(basePersona: string): string {
  return `${basePersona}

=========================================
🤫 MULTI-AGENT PROTOCOL: SILENT REVIEWER
=========================================
${CRITIC_AGENT_SYSTEM_PROMPT}`;
}